### ISSUE TITLE
Design error in create new listing

### ISSUE THREAD

**Issue by Raul-mz** [nirvanaitsolutions/swapsteem#127]
**Describe the bug**
When the FIAT option is selected in Market, more fields are added in the form and the form is superimposed on the Footer and Navbar

**To Reproduce**
1. Go to https://www.swapsteem.online/post-trade
2. Click on Market -> Fiat
3. See error

**Expected behavior**
The form was expected to expand but respecting the Footer and Navbar

**Screenshots**
![image](https://user-images.githubusercontent.com/9552217/52956206-06c81480-3365-11e9-801f-a1d6446a0e52.png)

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser Chrome
 - Version 72.0.3

**Comment by AneilPatel05** [comment]
It's a minor UI issue due to too many inputs in the column. We will fix it.

**Comment by AneilPatel05** [comment]
Fixed
