### ISSUE TITLE
Minor issue with menu text

### ISSUE THREAD

**Issue by mightypanda-x** [nirvanaitsolutions/swapsteem#128]
**Describe the bug**
First Navigation menu item should be spelled 'Crypto Market' instead of 'Crpto Market'

**To Reproduce**
1. Go to https://www.swapsteem.online/home
2. First menu item is spelled 'Crpto Market'

**Expected behavior**
Menu should be spelled 'Crypto Market'

**Screenshots**
![image](https://user-images.githubusercontent.com/13856451/52990948-46234f00-33bf-11e9-8855-3282fe472d11.png)

**Solution**
Change following line in /src/app/app-nav/app-nav.component.html
```html
<a class="nav-link" routerLink="market/crypto">Crpto Market</a>
```
To
```html
<a class="nav-link" routerLink="market/crypto">Crypto Market</a>
```
**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: OSX 10.11.6
 - Browser [e.g. chrome, safari]: Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by AneilPatel05** [comment]
Fixed
