### ISSUE TITLE
Able to remove/update items from buy/sell panels within home page when hitting API directly. 

### ISSUE THREAD

**Issue by tobias-g1** [nirvanaitsolutions/swapsteem#132]
**Describe the bug**
Currently, you have the ability to edit the details of trades for other users and in this scenario, I believe provide them information that corrupts their ability for them to be shown on the home page of the site. 

**To Reproduce**

1. Using postman enter the following https://swapsteem-api.herokuapp.com/listings/`{add any listing id here}`
2. Click on any trade shown on SwapSteem and get the listing Id from the URL. 
3. Replace the listing URL noted in the above URL with the listing Id gather from the listing on SwapSteem. 
4. Configure the following body into the request:

```
{"createdby":"anlptl","ad_type":"SELL","market":"CRYPTO","payment_method":"Crypto Transfer","to":"BTC","margin":1,"limit_from":0,"limit_to":0,"restricted_amounts":[],"from":"STEEM","ad_status":"open","ad_coin_amount":1,"terms":"1","ad_details":{"minimum_volume":0,"minimum_reputation_score":25,"new_buyer_limit":0,"track_liquidity":true},"security_details":{"identified_people_only":true,"identify_user_before_continuing_trade":true,"real_name_required":true,"sms_verification_required":true,"trusted_people_only":true},"payment_details":{"account_holder_name":"","account_number":0,"bank_name":"","bank_address":"","swift_bic_code":"","bank_code":"","paypal_email":"","upi_id":"","crypto_address":"2"}}
```
5. The request should be set to a PUT request and should have no authentication assoicated to it. 
6. Send the request within postman. 
7. Refresh the home page and note that listing Id you previously clicked is no longer shown on the home page. 

**Video**
The following video shows the issue in more detail:

https://www.youtube.com/watch?v=qD6DokokNhg&feature=youtu.be

#### Enviroment 
Browser: Google Chrome (Version 71.0.3578.98 (Official Build) (64-bit))
Device: MacBook Pro (Retina, 15-inch, Late 2013)
Operating system: MacOS Mojave Version 10.14.1 (18B75)

**Additional context**
Currently, there is no authentication that prevents a user from editing a trade, there should be authentication that checks to see if the users are A) who says he is and B) has the ability to edit that particular item. 

I would recommend adding a middleware than passes in the JWT token provided by SteemConnect prior to any PUT, POST, DELETE & PATCH (GET if you want it to) to verify that the user is who he says he is and then make another check to make sure that the user who you have verified is authenticated to edit that trade an example of the SteemConnect verification from one of the apps I did:

https://github.com/tobias-g1/contest-hero/blob/master/server/src/middleware/check-steemconnect.js

**Comment by tobias-g1** [comment]
This might have already been fixed as I message this to you on Discord, however, I thought it would be useful to have it here too for future references @nirvanaitsolutions

**Comment by nirvanaitsolutions** [comment]
Fixed
