### ISSUE TITLE
Add steemmonsters market - 100 steem + 1000 sweet

### ISSUE THREAD

**Issue by nirvanaitsolutions** [nirvanaitsolutions/swapsteem#155]
**Is your feature request related to a problem? Please describe.**
This is a new market Request. Steemmonsters.com is a card based game popular on steem. It has collectible cards that can be traded for steem or other currencies. We need to add ability to trade those monsters for steem/SBD.
**Describe the solution you'd like**
Add a new steemmonsters market page and link to it on top nav.
See peakmonsters.com or steemmonsters.com for market UI .
**Additional context**
We can not reuse the current UI as steemnsters have more  properties than coins/Fiat.

**Comment by AneilPatel05** [comment]
On hold for now
