### ISSUE TITLE
Create a vote selling market - 100 steem + 1000 sweet 

### ISSUE THREAD

**Issue by nirvanaitsolutions** [nirvanaitsolutions/swapsteem#156]
**Is your feature request related to a problem? Please describe.**
There are some services already that sell votes for SBD/steem like @booster, @smartsteem etc. We need a market to enable users sell their votes for steem/sbd.
**Describe the solution you'd like**
A market page for votes like current UI with some additional fields and custom vote price logic.

**Additional context**
Requested feature in beta.

**Comment by nirvanaitsolutions** [comment]
closing for now

**Comment by AneilPatel05** [comment]
Closing for now
