### ISSUE TITLE
Update the price API - 50 steem + 500 sweet

### ISSUE THREAD

**Issue by nirvanaitsolutions** [nirvanaitsolutions/swapsteem#158]
**Is your feature request related to a problem? Please describe.**
The price is derived from coingecko simple price API. Since we don't have direct pairs for many currencies on coingecko, listing some coins is not possible as of now. But we can get the current price of any token based on their price in btc and then converting to steem/SBD.
**Describe the solution you'd like**
For coins that do not have a pair, create a service to get price using btc. Get btc/coin price and convert it to steem/coin using the current btc/steem rate.

**Additional context**
This is blocking feature and needs to be resolved on priority.

**Comment by nirvanaitsolutions** [comment]
Reopened to fix

**Comment by AneilPatel05** [comment]
Done
