### ISSUE TITLE
Create an Android App from the source code - 100 steem + 1000 sweet

### ISSUE THREAD

**Issue by nirvanaitsolutions** [nirvanaitsolutions/swapsteem#159]
**Is your feature request related to a problem? Please describe.**
Having an Android app is must for a business like this. We already have a PWA that can be added to home screen for quick access, but an Android app will be better.
**Describe the solution you'd like**
Create an Android app using the current code and nativescript.

**Describe alternatives you've considered**
You can your way if you find it better than nativescript.
**Additional context**
App will be uploaded to play store, so it should properly signed and be ready for submission

**Comment by nirvanaitsolutions** [comment]
closing for now

**Comment by AneilPatel05** [comment]
To be reopened
