### ISSUE TITLE
Add BTS UIA  ( USER ISSUED ASSETS) market - 30 STEEM + 300 SWEET

### ISSUE THREAD

**Issue by AneilPatel05** [nirvanaitsolutions/swapsteem#173]
**Is your feature request related to a problem? Please describe.**
This is an enhancement to current application. BTS UIA are Bitshares based tokens that can be traded for any other Fiat or Cryptocurrencies. We need to add a market for BTS based UIA(tokens) and add OPEN.USD and BTS.BTC coins for now. We will add more UIAs later.
**Describe the solution you'd like**
Create a new market page for BTS User issued assets and provide a link in top nav.

Additional context
This should use the latest market UI

**Comment by nirvanaitsolutions** [comment]
Done
