### ISSUE TITLE
Create a Landing Page - 30 STEEM + 300 SWEET

### ISSUE THREAD

**Issue by AneilPatel05** [nirvanaitsolutions/swapsteem#174]
**Is your feature request related to a problem? Please describe.**
We need a separate landing page to display when the users visit our site. The landing page will contain all the information needed about our platform and links to various markets and utilities.
**Describe the solution you'd like
Create new home page accordjmg to the landing page design and add required links as directed by the PO. /home should display the landing page while /market/:id should show display the market in query.

**Additional context**
This enhancement needs to be deployed in the beta release.

**Comment by nirvanaitsolutions** [comment]
Partially Done
