### ISSUE TITLE
Replace the banner with market depth graph - 30 steem + 300 sweet

### ISSUE THREAD

**Issue by nirvanaitsolutions** [nirvanaitsolutions/swapsteem#175]
**Is your feature request related to a problem? Please describe.**
A market depth graph helps users understand the current liquidity of the pair in trade.
See the screenshot below for reference.

**Describe the solution you'd like**
Replace the current banner with a chart as shown in screenshots.

**Describe alternatives you've considered**
You can use canvas.js or any relevant library suitable.
![Screenshot from 2019-03-31 01-54-32](https://user-images.githubusercontent.com/30573340/55285347-fb9ad800-5357-11e9-90e5-904f086798d6.png)

**Additional context**
This will require the market page to be further split into pair pages. please see the related issue for info.

**Comment by AneilPatel05** [comment]
Postponed
