### ISSUE TITLE
Create a pair based page for trading view - 30 steem + 300 sweet

### ISSUE THREAD

**Issue by nirvanaitsolutions** [nirvanaitsolutions/swapsteem#176]
**Is your feature request related to a problem? Please describe.**
Instead of showing all currencies in a single market page, we need to create separate pages for each pair in a market as shown in below screenshot.
**Describe the solution you'd like**
Create a new route /market/?f=STEEM&t=ENG

**Describe alternatives you've considered**
Use the chart created in issue #175 in pair market view.
![Screenshot from 2019-03-31 01-59-20](https://user-images.githubusercontent.com/30573340/55285386-3bae8a80-5359-11e9-96d0-17fdea4b151f.png)
![Screenshot from 2019-03-31 01-59-41](https://user-images.githubusercontent.com/30573340/55285387-410bd500-5359-11e9-97d5-f3bb39a2ee1b.png)

**Additional context**
This feature is required in the beta.

**Comment by AneilPatel05** [comment]
Done
