### ISSUE TITLE
Add instant swap widget - 30 steem + 300 sweet

### ISSUE THREAD

**Issue by AneilPatel05** [nirvanaitsolutions/swapsteem#177]
**Is your feature request related to a problem? Please describe.**
The process of P2P conversion is a bit lengthy with introduction of third party escrow agent and dependency on the availability of the peer. To resolve this, we can provide an instant swap feature provided by onepagex.io
**Describe the solution you'd like**
Create a new page called instant swap and display the OnePageX.io widget on it. Provide a link to to the instant swap page in the top nav.
**Describe alternatives you've considered**
If possible please modify the design of page to match our color theme.
**Additional context**
This feature is required in the beta.
Code for widget 
```html
<div style="display: flex; justify-content: center;"><iframe src="https://onepagex.com/box/v1" width="800" height="400" style="border: none;">Unable To Load Widget</iframe></div>
```
Website : https://onepagex.com/onebox

![Screenshot_2019-03-31-13-21-09](https://user-images.githubusercontent.com/11619022/55286335-f79ea280-53b7-11e9-8311-214d5fddc474.png)

**Comment by nirvanaitsolutions** [comment]
done
