### ISSUE TITLE
Profile picture Does not load on any page

### ISSUE THREAD

**Issue by dongentle2** [nirvanaitsolutions/swapsteem#188]
**Describe the bug**
The profile image/avatar is not showing on the homepage and any of the pages. 

**To Reproduce**
1. Log into swapsteem with your steemit account. 
2. Check the avatar

**Expected behavior**
I expected the platform to display my profile picture Whenever I opened a page. 
**Screenshots**
![IMG_20190407_140037_434](https://user-images.githubusercontent.com/36037892/55684077-f5e85800-593e-11e9-849c-06b447df34ee.jpg)

**Smartphone (please complete the following information):**
 - Device: [infinix hot 5]
 - OS: [Android ]
 - Browser [Google Chrome ]
 - Version [7.0]

**Comment by AneilPatel05** [comment]
Fixed
