### ISSUE TITLE
Steem: USD option not loading 

### ISSUE THREAD

**Issue by dongentle2** [nirvanaitsolutions/swapsteem#189]
**Describe the bug**
The Steem: USD option is not taking any action after clicking.
**To Reproduce**
1. Go to 'the homepage after logging in '
2. Click on 'STEEM: USD'
3. See error

**Expected behavior**
I expected to be redirected to a steem: usd trade page but that didn't happen.

**possibly solution**
I suggest that the destination URL page be linked to the option to enable users access the target destination.

**Screenshots**
Below is a video 

https://youtu.be/GBUhnHdJA48

**Smartphone (please complete the following information):**
 - Device: [infinix hot 5]
 - OS: [Android ]
 - Browser [Google Chrome ]
 - Version [7.0]

**Comment by AneilPatel05** [comment]
Fixed
