### ISSUE TITLE
The SBD: USD option not working 

### ISSUE THREAD

**Issue by dongentle2** [nirvanaitsolutions/swapsteem#190]
**Describe the bug**
The SBD: USD option is not taking any action after clicking.
**To Reproduce**
1. Go to 'the homepage after logging in '
2. Click on 'SBD: USD'
3. See error

**Expected behavior**
I expected to be redirected to a SBD: USD trade page but that didn't happen.

**possibly solution**
I suggest that the destination URL page be linked to the option to enable users access the target destination.

**Screenshots**
Below is a video 

https://youtu.be/_QsdnkIcYoA

**Smartphone (please complete the following information):**
 - Device: [infinix hot 5]
 - OS: [Android ]
 - Browser [Google Chrome ]
 - Version [7.0]

**Comment by AneilPatel05** [comment]
Fixed
