### ISSUE TITLE
Convert design to code - 100 steem + 1000 sweet

### ISSUE THREAD

**Issue by nirvanaitsolutions** [nirvanaitsolutions/swapsteem#2]
The design for the application is done and we need to convert it into actual web user interface.
Design files can be found in the url provided.

**Comment by nirvanaitsolutions** [comment]
need the notifications screen

**Comment by nirvanaitsolutions** [comment]
Done.

**Comment by AneilPatel05** [comment]
Please move the create a listing button inside the markets @bunyy

**Comment by AneilPatel05** [comment]
Replace the banner with market depth chart based on dynamic data

**Comment by nirvanaitsolutions** [comment]
Remaining tasks moved to individual issues. Closing.
