### ISSUE TITLE
Site doesn't load via https://

### ISSUE THREAD

**Issue by tobias-g1** [nirvanaitsolutions/swapsteem#52]
**Describe the bug**
Attempting to load the site via https:// doesn't work a user cannot view the site.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.swapsteem.online/ 

or 

1. https://swapsteem.online (as specified in the bio)

**Expected behaviour**
A user should be able to access the site via https://, the fact this site holds bank details and doesn't work https:// is quite an issue. 

**Screenshots**

Browser: Google Chrome (Version 71.0.3578.98 (Official Build) (64-bit))
Device: MacBook Pro (Retina, 15-inch, Late 2013)
Operating system: MacOS Mojave Version 10.14.1 (18B75)

**Additional context**
If you've got specific issues with it not working via https:// let me know as I had some troubles to when working with Heroku.

**Comment by nirvanaitsolutions** [comment]
Another valid bug. We should provide as much security as possible.

**Comment by nirvanaitsolutions** [comment]
@tobias-g1 please test with https now. It works. Thank you for letting us know.
