### ISSUE TITLE
Profile Images don't load on wallet

### ISSUE THREAD

**Issue by tobias-g1** [nirvanaitsolutions/swapsteem#53]
**Describe the bug**
When viewing a users profile on the profile page, the profile image doesn't display correctly. 

**To Reproduce**
1. Go to your wallet.
2. Note that the profile image doesn't load. 

I suspect this isn't happening to every user, this may not be able to replicate. 

**Expected behaviour**
A user's profile image should always be displayed correctly. 

**Screenshots**
The following screenshot provides additional clarity surrounding the issue:

![image](https://user-images.githubusercontent.com/17148879/51773771-d08dd100-20e7-11e9-8053-e1da8bae7d0c.png)

Browser: Google Chrome (Version 71.0.3578.98 (Official Build) (64-bit))
Device: MacBook Pro (Retina, 15-inch, Late 2013)
Operating system: MacOS Mojave Version 10.14.1 (18B75)

A simple a more flexible solution would replace:

this.profile_url = this.profile && this.profile.profile ? this.profile.profile.profile_image : '';

so that the profile image is no longer pulled from the json_metadata, this prevents a number of issues that can pop up surrounding profile images not being loaded correctly. If you instead use:

`https://steemitimages.com/u/${username}/avatar`

This would also handle broken images with a fallback.

**Comment by nirvanaitsolutions** [comment]
@bunyy I'll fix this.

**Comment by nirvanaitsolutions** [comment]
@Ayushnita please solve this bug related to your code

**Comment by nirvanaitsolutions** [comment]
@AyushAgrawal104

**Comment by AyushAgrawal104** [comment]
I am working on this

**Comment by nirvanaitsolutions** [comment]
@bunyy canyou fix it asap?
