### ISSUE TITLE
Account holder name value bound to same data as SWIFT/BIC code

### ISSUE THREAD

**Issue by tobias-g1** [nirvanaitsolutions/swapsteem#54]
**Describe the bug**
If you type in the name field within a BUY type trade, the SWIFT/BIC code value will also be filled. 

**To Reproduce**
1. Sign into Swapsteem & select post a trade
2. Select ad type as buy
3. Enter a name
4. Note that SWIFT/BIC code is also filled in. 

**Expected behavior**
Each item within a form should be bound to its own data. 

**Screenshots**
The following GIF helps show this issue in more detail:

![jan-25-2019 21-38-43](https://user-images.githubusercontent.com/17148879/51774285-a3dab900-20e9-11e9-881d-5f9862e5b402.gif)

**Desktop (please complete the following information):**
Browser: Google Chrome (Version 71.0.3578.98 (Official Build) (64-bit))
Device: MacBook Pro (Retina, 15-inch, Late 2013)
Operating system: MacOS Mojave Version 10.14.1 (18B75)

**Comment by nirvanaitsolutions** [comment]
Valid minor bug due to faulty variable assignment. Assigned @Shubh1692
