### ISSUE TITLE
Add Steem account creation Feature

### ISSUE THREAD

**Issue by nirvanaitsolutions** [nirvanaitsolutions/swapsteem#76]
**Is your feature request related to a problem? Please describe.**
In order to use swapsteem, it is mandatory to have a steem account. I want to a Sign Up feature to enable users create Steem accounts instantly by paying via debit/credit card.

**Describe the solution you'd like**
We need a Sign-Up button when the user is logged out. The sign-up button should redirect the user to an account creation page/modal as per the steem.account.ninja API.

**Describe alternatives you've considered**
We can implement account creation from our own RC in the future. 

**Additional context**
Check the account creation feature on steempeak.com

**Comment by Shubh1692** [comment]
#76 Has been merged in PR https://github.com/nirvanaitsolutions/swapsteem/pull/88
