### ISSUE TITLE
Need content for Help, Faq, ToS and tutorials page

### ISSUE THREAD

**Issue by nirvanaitsolutions** [nirvanaitsolutions/swapsteem#8]
We need the following content : 

- FAQ( Frequently asked questions ) 
- ToS ( Terms of Service )
- Tutorials ( How To's)

Contributors can refer http://localbitcoins.com for reference since our business model is similar to theirs in some features.

**Comment by frankremmy** [comment]
@nirvanaitsolutions I'll start with the FAQ.

**Comment by frankremmy** [comment]
Hi,
Hi
Here's the link to the file:
https://1drv.ms/w/s!AmsMPZ07DfJ-gSXCdANoQFYgSvO6

**Comment by frankremmy** [comment]
Restructured the whole document. You can find it [here. ](
https://1drv.ms/w/s!AmsMPZ07DfJ-gSf8dmFpViuHYMeW)

**Comment by nirvanaitsolutions** [comment]
done by @frankremmy
