### ISSUE TITLE
Responsive UI for mobile friendly app

### ISSUE THREAD

**Issue by nirvanaitsolutions** [nirvanaitsolutions/swapsteem#96]
**Is your feature request related to a problem? Please describe.**
Right now, The application is not optimized for UI designs. We need to make it responsive to look good on smartphones and tablet browsers.

**Describe the solution you'd like**
Use Angular Material for responsiveness.

**Describe alternatives you've considered**
We have bootstrap already installed but not configured. As an alternative.

**Comment by AneilPatel05** [comment]
Done
